# Default values for zipkin.
collector:
  replicaCount: 2
  maxReplicaCount: 2
  targetCPUUtilizationPercentage: 80
  imageVersion: 1.31.1
  sampleRate: 0.1
  probeStartupDelay: 100
  queryPort: 9411
  resources:
    ramMb: 900
    javaOptsHeap: 700
    cpuRequest: 80m
    cpuLimit: 300m

ui:
  replicaCount: 1
  imageVersion: 1.31.1
  probeStartupDelay: 100
  queryPort: 9411
  resources:
    ramMb: 900
    javaOptsHeap: 700
    cpuRequest: 150m
    cpuLimit: 300m

dependencies:
  enabled: false
  cron: "0 22 * * *"
  imageVersion: 1.9.0
  resources:
    ramMb: 900
    javaOptsHeap: 700
    cpuRequest: 150m
    cpuLimit: 200m

configmap:
  name: zipkin-storage
  contactPoints:
    name: zipkin-storage
    key: cassandra.contactpoints
  username:
    name: zipkin-storage
    key: cassandra.username
  localdc:
    name: zipkin-storage
    key: cassandra.localdc

ingress:
  class: "istio"
  host: placeholder
  path: /.*
  serviceName: zipkin-ui
  servicePort: 9411

storageMethod: cassandra

cassandra:
  username: zipkin
  password: zipkin
  contactPoints: zipkin-cassandra:9042
  localdc: datacenter1
  ensureSchema: false
  image: openzipkin/zipkin-cassandra
  probeStartupDelay: 120
  tag: 1
  replicas: 1
  pvSize: 20Gi
  storageClassName: cephfs
  resources:
    ramMb: 3000
    cpuRequest: 200m
    cpuLimit: 500m

node:
  cpus: 2


