apiVersion: v1
kind: Secret
metadata:
  name: zipkin
  labels:
    app: zipkin
  # This declares the resource to be a hook. By convention, we also name the
  # file "pre-install-XXX.yaml", but Helm itself doesn't care about file names.
type: Opaque
data:
  cassandra.password: emlwa2luCg==