apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin-collector
  labels:
    app: zipkin-collector
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: zipkin-collector
    spec:
      containers:
        - name: zipkin-collector
          image: "reg.lifesense.com/openzipkin/zipkin:1.31.1"
          ports:
            - containerPort: 9411
          livenessProbe:
            initialDelaySeconds: 100
            tcpSocket:
              port: 9411
          readinessProbe:
            initialDelaySeconds: 100
            httpGet:
              path: /health
              port: 9411
          resources:
            limits:
              cpu: "300m"
              memory: "900Mi" # TODO fix this, this field id mi but the value is mb. There will be slight wastage
            requests:
              cpu: "80m"
              memory: "900Mi" # TODO fix this, this field id mi but the value is mb. There will be slight wastage
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: QUERY_PORT
              value: "9411"
            - name: JAVA_OPTS
              value: "-XX:ConcGCThreads=2 -XX:ParallelGCThreads=2 -Djava.util.concurrent.ForkJoinPool.common.parallelism=2 -Xms700M -Xmx700M -XX:+UseG1GC -server"
            - name: COLLECTOR_SAMPLE_RATE
              value: "0.1"
            - name: QUERY_ENABLED
              value: "false"
            - name: STORAGE_TYPE
              value: "cassandra"
            - name: CASSANDRA_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: zipkin-storage
                  key: cassandra.username
            - name: CASSANDRA_CONTACT_POINTS
              valueFrom:
                configMapKeyRef:
                  name: zipkin-storage
                  key: cassandra.contactpoints
            - name: CASSANDRA_LOCAL_DC
              valueFrom:
                configMapKeyRef:
                  name: zipkin-storage
                  key: cassandra.localdc
            - name: CASSANDRA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zipkin
                  key: cassandra.password
            - name: CASSANDRA_ENSURE_SCHEMA
              value: "false"