kind: Service
apiVersion: v1
metadata:
  name: zipkin
  labels:
      app: zipkin
spec:
  ports:
   - port: 9411
     name: "http"
     targetPort: 9411
  selector:
    app: zipkin-collector
---    
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin-collector
  labels:
    app: zipkin-collector
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  template:
    metadata:
      labels:
        app: zipkin-collector
    spec:
      containers:
        - name: zipkin-collector
          image: "reg.lifesense.com/openzipkin/zipkin:latest"
          ports:
            - containerPort: 9411
          livenessProbe:
            initialDelaySeconds: 100
            tcpSocket:
              port: 9411
          resources:
            limits:
              cpu: "300m"
              memory: "900Mi" # TODO fix this, this field id mi but the value is mb. There will be slight wastage
            requests:
              cpu: "80m"
              memory: "900Mi" # TODO fix this, this field id mi but the value is mb. There will be slight wastage
          env:
            - name: STORAGE_TYPE
              value: "cassandra"
            - name: CASSANDRA_CONTACT_POINTS
              value: "zipkin-cassandra"