kind: Service
apiVersion: v1
metadata:
  name: zipkin-ui
  labels:
      app: zipkin-ui
spec:
  ports:
   - port: 80
     name: "http"
     targetPort: 80
  selector:
    app: zipkin-ui
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zipkin-ui
  labels:
    app: zipkin-ui
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 2
  template:
    metadata:
      labels:
        app: zipkin-ui
    spec:
      containers:
        - name: zipkin-ui
          image: "reg.lifesense.com/openzipkin/zipkin-ui:latest"
          ports:
            - containerPort: 80
          livenessProbe:
            initialDelaySeconds: 100
            tcpSocket:
              port: 80
          resources:
            limits:
              cpu: "300m"
              memory: "900Mi" # TODO fix this, this field id mi but the value is mb. There will be slight wastage
            requests:
              cpu: "800m"
              memory: "900Mi" # TODO fix this, this field id mi but the value is mb. There will be slight wastage
          env:
            - name: ZIPKIN_BASE_URL
              value: "http://zipkin:9411"